# Generated by Django 3.2.8 on 2021-10-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=264, null=True, verbose_name='Put A Title')),
                ('slug', models.CharField(blank=True, max_length=264, null=True, unique=True)),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name="what's on your mind")),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Image')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
