# Generated by Django 3.2.8 on 2021-10-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Image'),
        ),
    ]
