# Generated by Django 3.2.8 on 2021-10-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
